### ISSUE TITLE
还有一个认证的小bug

### ISSUE THREAD

**Issue by 00xdF** [Deali-Axy/StarBlog#10]
还有一个小问题，github中jwt认证里面的配置文件和你服务器的配置参数是一样的，这是不安全的。
![图片](https://user-images.githubusercontent.com/110643835/236591873-6a6b6bba-a75b-4d08-8d06-32ee562b642b.png)
可以通过生成令牌模拟管理员操作
![图片](https://user-images.githubusercontent.com/110643835/236591674-5f26e03c-9d7a-43e4-982f-36eab123c73d.png)

**Comment by Deali-Axy** [comment]
昨天修复漏洞的时候忘记改了😂

**Comment by Deali-Axy** [comment]
已修复，感谢~

**Comment by 00xdF** [comment]
😁👍

**Comment by Deali-Axy** [comment]
欢迎大佬继续提供bug线索😂

**Comment by 00xdF** [comment]
你才是大佬，向你学习😍

**Comment by Deali-Axy** [comment]
说笑了，都是搬砖工程师哈哈🤝

**Comment by 00xdF** [comment]
哈哈 加油加油🤣
