### ISSUE TITLE
使用PostgreSQL，应该改代码里的哪几个地方？老哥能给指个路吗

### ISSUE THREAD

**Issue by namiotaka** [Deali-Axy/StarBlog#19]
开发大佬，我云服务器上用的是PostgreSQL，我想问下，代码除了connection string，还有哪几个地方需要改一下才可以连接呢？

**Comment by Deali-Axy** [comment]
事实上，我部署的博客也是使用 PostgreSql 数据库。

项目代码里已经配置好了这三个数据库的支持：

- SQLite
- MySQL
- PostgreSql

编辑 `StarBlog.Data/Extensions/ConfigureFreeSql.cs` 文件

取消 `var freeSql = FreeSqlFactory.CreatePostgresSql(configuration.GetConnectionString("PostgresSql"));` 这一行的注释即可

![](https://github.com/Deali-Axy/StarBlog/assets/11494144/3890925d-e2f9-49e9-a67b-ffdbabbe70c3)

**Comment by namiotaka** [comment]
大佬，那我这几个包装到哪个目录下？
dotnet add package Microsoft.EntityFrameworkCore
dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL
dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL.Design

**Comment by Deali-Axy** [comment]
不需要安装以额外的包。

本项目使用的ORM是FreeSQL，你添加的这个是EFCore，不需要。

配置好数据库之后打开数据结构自动同步即可自动建表了。

后续上线生产环境把自动同步关掉即可。

**Comment by namiotaka** [comment]
好的，完美解决了，谢谢大佬。
