### ISSUE TITLE
缺少文件wwwroot/lib

### ISSUE THREAD

**Issue by 1216654348** [Deali-Axy/StarBlog#2]
缺少文件wwwroot/lib，可以提交一下吗，非常感谢

**Comment by Deali-Axy** [comment]
你好，本项目的前端资源使用 NPM + Gulp 管理，请根据 readme.md 文档中的“前端资源”部分进行操作获取前端依赖~

**Comment by 1216654348** [comment]
嗯嗯   好的，看了说明，非常感谢
