### ISSUE TITLE
作者你好 这个系统有个小小的漏洞

### ISSUE THREAD

**Issue by 00xdF** [Deali-Axy/StarBlog#9]
在博客上传那里没加认证注解 会导致未授权上传博客的漏洞

下面是我测试的结果：
https://blog.sblt.deali.cn:9000/Blog/Post/a8043d990d20544e

![图片](https://user-images.githubusercontent.com/110643835/236450566-b6ba4c79-ff7c-4cfb-acce-2aa35451b6fe.png)

**Comment by Deali-Axy** [comment]
感谢指出，已修复
